### ISSUE TITLE
Add legend for choropleth and change color scheme

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#113]
We need to add legends to what the each color means in the choropleth. 
In our current Map we do not know what each color means. 

**Current choropleth**
![image](https://cloud.githubusercontent.com/assets/1731313/9774502/1224c6a8-5717-11e5-8dda-404573da4b39.png)

**Expected choropleth**
![us_heatmap](https://cloud.githubusercontent.com/assets/1731313/9774528/342d5d8c-5717-11e5-907d-7de1a99d647e.jpg)

**Comment by senthilkumar2githup** [comment]
@dineshshetye we can close this one.
