### ISSUE TITLE
Ability to drill down into dashboards

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#22]
We should be able to drill-down into more details in a particular dashboard.
For e.g. We can have one dashboard that shows a multiple records. When the user clicks on a record he should be able to see more details of the selected record.

**Comment by drealeed** [comment]
Is this the same as HIPIE issue https://github.com/hpcc-systems/HIPIE/issues/380  or https://github.com/hpcc-systems/HIPIE/issues/381?

```
  From: Dinesh Shetye <notifications@github.com>
```

 To: hpcc-systems/Dashboard Dashboard@noreply.github.com 
 Sent: Wednesday, February 4, 2015 11:14 AM
 Subject: [Dashboard] Ability to drill down into dashboards (#22)

We should be able to drill-down into more details in a particular dashboard.
For e.g. We can have one dashboard that shows a multiple records. When the user clicks on a record he should be able to see more details of the selected record. —

**Comment by dineshshetye** [comment]
@drealeed This is related to Dashboard_1.0 (which does not use HIPIE).

**Comment by dineshshetye** [comment]
Not needed as of now.
