### ISSUE TITLE
Every widget must have a horizontal and vertical scroll bar

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#26]
Every widget must have a horizontal/vertical scroll bar. When you click on maximize icon the chart should cover the entire area.

![image](https://cloud.githubusercontent.com/assets/1731313/6196820/9dbff82e-b3aa-11e4-8bae-89ca2a80e6db.png)

![image](https://cloud.githubusercontent.com/assets/1731313/6196874/3a24cab4-b3ab-11e4-8c42-5d8bf5c5706f.png)

**Comment by RajalakshmiElumalaiCts** [comment]
Scroll bars will appear only for Table widgets. There is already horizontal scroll bar in place that appears when you hover over the widget. Vertical scrolling is not needed as we have pagination.
A bar chart or pie chart should fit in the area, we shouldn't have scrolling for such charts.

Will make the widgets occupy entire screen when maximized.

**Comment by dineshshetye** [comment]
Tested and Works.
