### ISSUE TITLE
Input Parameters drop-down for the chart must not be sorted

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#50]
For the "Input Parameters" drop down the input fields are being sorted alphabetically. We need to display as it appears in the ROXIE query. 

**As it appears in the query:**
![image](https://cloud.githubusercontent.com/assets/1731313/8196158/c531342e-1456-11e5-82ab-8b69fc7d6296.png)

**As it appears in Input parameters drop down:**
![image](https://cloud.githubusercontent.com/assets/1731313/8196132/6fa2e53e-1456-11e5-9eb0-78b3bbe4a64b.png)

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye 
Please refer the closed issue #34

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye 
For Non generic queries, the input parameters will be in the order as in HPCC cluster.
For generic queries,the ' fetch_input_parameters ' query returns input parameters in sorted order.So 'fetch_input_parameters' query response needs to be changed

**Comment by dineshshetye** [comment]
@RajalakshmiElumalaiCts I think the best approach is to return the list of fields as it is in the ROXIE query (No matter if it is generic or non-generic query).

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye  We are not getting list of input parameters from roxie. 'fetch_input_parameters' is returning us the list of parameters. This query has to be modified in HPCC to return by ROXIE order.

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye  As discussed in call, the 'fetch_input_parameters' query need to be  modified to return the input parameters in the order as in original roxie query.

**Comment by dineshshetye** [comment]
The order of columns is maintained as returned by the 'fetch_input_parameters' query. If the user wants to have a specific order he has to change the 'fetch_input_parameters' query.
