### ISSUE TITLE
The Common filters drop is not is not populating

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#51]
The Common filters drop is not is not populating for query **attributemonitor_generic_ir20** 

![image](https://cloud.githubusercontent.com/assets/1731313/8196190/1c79843e-1457-11e5-926c-b409e21996e9.png)

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye 
The Input parameters for query will get displayed in filter panel, only when the query returns multiple values for the input parameter.

**Comment by dineshshetye** [comment]
@RajalakshmiElumalaiCts The Common Filter should work as follows:
1. If the query returns multiple values display them (which we are doing currently)
2. If the query does not return any values display text boxes where the user can enter the values in text box and chart will be refreshed accordingly.

In the below screenshot modelId and year should be text boxes in the Common Filter.

![image](https://cloud.githubusercontent.com/assets/1731313/8223459/db1d5318-1545-11e5-9088-24b6611a2dff.png)
