### ISSUE TITLE
Chloropleth chart not working

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#56]
These are the i/p to the chart:
Query: attributemonitor_generic_ir24
Chart Measures: Total
Chart Attributes: State
Input Parameters: ModelID -> A016

![image](https://cloud.githubusercontent.com/assets/1731313/8220269/fb0a922a-151e-11e5-960e-fa61794a79fd.png)

**Comment by dineshshetye** [comment]
Chloropleth is getting rendered but it is not showing different colors based on the value for the below query. 

**NOTE:** The  attributemonitor_fetch_input_parameters query is changed to return proper values.

There is a javascript error as well:

``` javscript
Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '.2014' is not a valid selector.
```

Query: attributemonitor_generic_ir24
Chart Measures: Total
Chart Attributes: State
Input Parameters: ModelID -> A016

![image](https://cloud.githubusercontent.com/assets/1731313/8263746/d755b84e-16ab-11e5-89bc-7ae10185ab4e.png)

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye 
If we give value '2014' fot the input parameter 'year', getting chart with colours as well as with values.
