### ISSUE TITLE
Chart not populating"Secondary Chart Measures" column values

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#58]
The chart below is not populating "Secondary Chart Measures" column values. Although the chart is being displayed with the actual values and the db also has correct values. 
When we click on the icon to add Secondary Chart Measure option the values (bmk_rangepercent & cur_rangepercent) show up but the 'Hide secondary Y-Axis' is un-selected (the user had selected it initially). Also after reviewing the string that is stored in the db it looks like we are not storing the 'show/hide secondary Y-Axis' value.

**String store in db**

``` xml
<attribute column="scorerange" displayName="scorerange" fileName="qb633dbd_generic_str"/>
    <isAxisrotated>false</isAxisrotated>
    <isGrouped>false</isGrouped>
    <measures aggregateFunction="none" column="psi" fileName="qb633dbd_generic_str" isSecondary="false">
        <displayYColumnName>PSI</displayYColumnName>
    </measures>
    <measures aggregateFunction="none" column="bmk_rangepercent" fileName="qb633dbd_generic_str" isSecondary="true">
        <displayYColumnName>BM pcnt</displayYColumnName>
    </measures>
    <measures aggregateFunction="none" column="cur_rangepercent" fileName="qb633dbd_generic_str" isSecondary="true">
        <displayYColumnName>Actual pcnt</displayYColumnName>
    </measures>
    <yThresholdValMax>0.07</yThresholdValMax>
    <yThresholdValMin>0.02</yThresholdValMin>
```

LineChart:
Query: qb633dbd_generic_str
Chart Measures: PSI
Secondary Chart Measures: bmk_rangepercent & cur_rangepercent
Chart Attribute: scorerange 
InputParameters:
bmk_month = 07
bmk_year = 2014
cur_month = 08
cur_year = 2014
State = GA
ModelID = A030

![image](https://cloud.githubusercontent.com/assets/1731313/8240817/57e4e216-15d3-11e5-972e-6db8b6e64aaf.png)

![image](https://cloud.githubusercontent.com/assets/1731313/8240882/cec08552-15d3-11e5-9c59-a7fe80474f03.png)

**Comment by RajalakshmiElumalaiCts** [comment]
@dineshshetye 

Couldn't recreate the scenario
