### ISSUE TITLE
Values are being rounded on the hover over pop-up.

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#71]
All the values (BMK Percent, Actual Percent, PSI_None, PSI_High, PSI_Low) are being rounded on the hover over pop-up. We should not round up any values.

![image](https://cloud.githubusercontent.com/assets/1731313/8726866/b3b48172-2baa-11e5-9c4b-9336b15ccabd.png)

**Comment by Ilakkiya-Sivaraj** [comment]
resolved this in
https://github.com/senthilkumar2githup/Dashboard/commit/fed75d23db93aa3245dca3366ca25f392b044dc8

**Comment by Ilakkiya-Sivaraj** [comment]
Now the values like 0.07000000000000001  are rounded  to 0.070 because D3 doesn't have the ability to give that much precision.
